/**
 * Copies database/scheme_rules.json into src/lib/triage/ so the app can
 * import it statically.
 *
 * Why not read it from disk at runtime? A dynamic readFileSync makes Turbopack
 * trace the entire project into the server bundle, and it makes the verdict
 * depend on the deployed filesystem layout. A static import gets the policy
 * baked into the build, which suits a file that only changes when a circular
 * changes.
 *
 * database/scheme_rules.json stays the single source of truth. The copy is
 * git-ignored and regenerated by predev/prebuild/pretest, so it cannot drift.
 */
import { copyFileSync, mkdirSync } from "node:fs";
import path from "node:path";

const source = path.join(import.meta.dirname, "..", "..", "database", "scheme_rules.json");
const targetDir = path.join(import.meta.dirname, "..", "src", "lib", "triage");
const target = path.join(targetDir, "scheme_rules.json");

mkdirSync(targetDir, { recursive: true });
copyFileSync(source, target);

console.log(`Synced scheme rules -> ${path.relative(process.cwd(), target)}`);
