#!/usr/bin/env python
"""Export a compiled rule pack from Postgres to database/rule_pack.json.

`rule_pack.json` is a generated artifact: the compiled output of
kh.compile_pack(), committed so the engine can boot and be unit-tested with no
database, and so it can serve as the offline fallback. This script is the only
thing that should ever write it.

    python database/export_pack.py NFSP-2026_SHORT_RAINS-0001
    python database/export_pack.py NFSP-2026_SHORT_RAINS-0001 --check

--check exits non-zero if the committed file differs from the database, which is
what CI runs to catch a hand-edit or an un-exported policy change.
"""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import sys

import psycopg

HERE = pathlib.Path(__file__).resolve().parent
TARGET = HERE / "rule_pack.json"

# Stable, human-readable top-level order. Anything unlisted is appended.
KEY_ORDER = [
    "pack_version",
    "engine_contract",
    "scheme",
    "season",
    "counties",
    "depots",
    "documents",
    "fertilizers",
    "allocation",
    "prices",
    "rules",
    "citations",
]

ANNOTATIONS = {
    "_generated": (
        "Generated by database/export_pack.py from kh.compile_pack(). Do not "
        "hand-edit. Edit the authoring tables and re-export. Committed so the "
        "engine can boot and be unit-tested with no database, and as the "
        "offline fallback if the database is unreachable."
    ),
}


def fetch(dsn: str, version: str) -> tuple[dict, str, bool]:
    with psycopg.connect(dsn) as conn, conn.cursor() as cur:
        cur.execute(
            "select payload::text, checksum, published_at is not null "
            "from kh.rule_pack where version = %s",
            (version,),
        )
        row = cur.fetchone()
    if row is None:
        sys.exit(f"no rule pack {version!r} in the database")
    return json.loads(row[0]), row[1], row[2]


def render(payload: dict, published: bool) -> str:
    doc: dict = dict(ANNOTATIONS)
    doc["_environment"] = "production" if published else "development-fixture"
    if not published:
        unverified = sorted(
            cid
            for cid, c in payload.get("citations", {}).items()
            if c.get("source_type") in ("UNVERIFIED", "PRESS")
        )
        doc["_warning"] = (
            "Not publishable. These citations are not traceable to a gazette "
            "notice or circular: " + ", ".join(unverified)
        )
    for key in KEY_ORDER:
        if key in payload:
            doc[key] = payload[key]
    for key in payload:
        if key not in doc:
            doc[key] = payload[key]
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("version")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--dsn", default=os.environ.get("DATABASE_URL"))
    args = ap.parse_args()

    if not args.dsn:
        sys.exit("set DATABASE_URL or pass --dsn")

    payload, checksum, published = fetch(args.dsn, args.version)
    rendered = render(payload, published)

    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != rendered:
            print(
                f"{TARGET.name} is out of date with rule pack {args.version}.\n"
                f"Run: python database/export_pack.py {args.version}",
                file=sys.stderr,
            )
            return 1
        print(f"{TARGET.name} matches {args.version} (checksum {checksum[:12]}…)")
        return 0

    TARGET.write_text(rendered, encoding="utf-8", newline="\n")
    state = "published" if published else "UNPUBLISHED fixture"
    print(f"wrote {TARGET.name} from {args.version} ({state}, checksum {checksum[:12]}…)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
